---
- hosts: server2.abc.com
  remote_user: test1
  become: true
  tasks:
   - name: install httpd package
     command: yum install httpd -y
   - name: copy index.html
     shell: echo "hi" > /var/www/html/index.html
   - name: start httpd service
     raw: systemctl start httpd  
   - name: execute script
     script: ./xyz.sh
