---
- hosts: webserver
  remote_user: test1
  become: true
  tasks:
   - name: install httpd package
     yum: name=httpd state=installed
   - name: copy index.html
     copy: src=index.html dest=/var/www/html/index.html
     notify: restart httpd service
   - name: start httpd service
     service: name=httpd state=started
  handlers:
   - name: restart httpd service
     service: name=httpd state=restarted 
