---
- hosts: server2.abc.com
  remote_user: test1
  become: true
  tasks:
   - name: install httpd package
     yum: name={{item}} state=installed
     with_items:
        - httpd
        - curl
        - telnet
